# Generated by Django 3.1.7 on 2021-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=200)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('academic_advisor', models.CharField(blank=True, max_length=200)),
                ('academic_advisor_email', models.EmailField(blank=True, max_length=200)),
                ('question1', models.CharField(choices=[('qone', 'What was the first job you wanted as a kid?'), ('qtwo', 'If you were one of the seven dwarves in Snow White, which one would you be?'), ('qthree', 'What is your guilty pleasure?'), ('qfour', 'What song do you sing in the shower?'), ('qfive', 'What is your biggest (non-serious) fear?'), ('qsix', 'What is your favorite binge-watching TV series?'), ('qseven', 'What would your last meal on Earth be?'), ('qeight', 'Who is your favorite person in history?'), ('qnine', 'A trip you most want to take but haven’t yet?')], max_length=200)),
                ('answer1', models.TextField(blank=True, max_length=1000, null=True)),
                ('question2', models.CharField(choices=[('qone', 'What was the first job you wanted as a kid?'), ('qtwo', 'If you were one of the seven dwarves in Snow White, which one would you be?'), ('qthree', 'What is your guilty pleasure?'), ('qfour', 'What song do you sing in the shower?'), ('qfive', 'What is your biggest (non-serious) fear?'), ('qsix', 'What is your favorite binge-watching TV series?'), ('qseven', 'What would your last meal on Earth be?'), ('qeight', 'Who is your favorite person in history?'), ('qnine', 'A trip you most want to take but haven’t yet?')], max_length=200)),
                ('answer2', models.TextField(blank=True, max_length=1000, null=True)),
                ('question3', models.CharField(choices=[('qone', 'What was the first job you wanted as a kid?'), ('qtwo', 'If you were one of the seven dwarves in Snow White, which one would you be?'), ('qthree', 'What is your guilty pleasure?'), ('qfour', 'What song do you sing in the shower?'), ('qfive', 'What is your biggest (non-serious) fear?'), ('qsix', 'What is your favorite binge-watching TV series?'), ('qseven', 'What would your last meal on Earth be?'), ('qeight', 'Who is your favorite person in history?'), ('qnine', 'A trip you most want to take but haven’t yet?')], max_length=200)),
                ('answer3', models.TextField(blank=True, max_length=1000, null=True)),
                ('prefer_sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('no preference', 'no preference')], max_length=200)),
                ('geographical', models.CharField(choices=[('EPA/MV', 'EPA/MV'), ('MP/RC', 'MP/RC'), ('SM', 'SM'), ('No preference', 'No preference')], max_length=200)),
                ('commit', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('seminar', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('reason', models.ManyToManyField(blank=True, related_name='reasons', to='mprofiles.Reason')),
            ],
        ),
    ]
