# Generated by Django 3.1.7 on 2021-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0004_session_sessionsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
