# Generated by Django 3.1.7 on 2021-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0005_session_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='sessionsupports', to='mprofiles.Sessionsupport'),
        ),
    ]
