# Generated by Django 3.1.7 on 2021-05-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0006_auto_20210526_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
