# Generated by Django 3.1.7 on 2021-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0008_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
