# Generated by Django 3.1.7 on 2021-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0013_student_know'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='available',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='commit',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='seminar',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
