# Generated by Django 3.1.7 on 2021-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0015_mentor_spanish'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='hear',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='know',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='partner',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='reason',
        ),
        migrations.AddField(
            model_name='mentor',
            name='reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Mentorreason',
        ),
    ]
