# Generated by Django 3.1.7 on 2021-06-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0018_auto_20210619_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='check_bridge',
        ),
    ]
