# Generated by Django 3.1.7 on 2021-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0019_remove_mentor_check_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='check',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
