# Generated by Django 3.1.7 on 2021-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0020_mentor_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
