# Generated by Django 3.1.7 on 2021-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0021_mentor_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='cont',
            new_name='dialogue',
        ),
        migrations.AddField(
            model_name='session',
            name='elaborate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='meaningful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='urgent',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
