# Generated by Django 3.1.7 on 2021-06-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0026_auto_20210620_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
