# Generated by Django 3.1.7 on 2021-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0027_auto_20210620_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='understand',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
