# Generated by Django 3.1.7 on 2021-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0028_auto_20210710_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='ethnic',
            field=models.CharField(blank=True, choices=[('African American or Black', 'African American or Black'), ('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian American', 'Asian American'), ('Caucasian or White', 'Caucasian or White'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('I prefer not to say', 'I prefer not to say')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='partner',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('unsure', 'unsure')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='spanish',
            field=models.CharField(blank=True, choices=[('Not at all', 'Not at all'), ('Low (can make basic conversation)', 'Low (can make basic conversation)'), ('Medium (somewhat fluent)', 'Medium (somewhat fluent)'), ('High (proficient enough to have a lengthy and detailed conversation)', 'High (proficient enough to have a lengthy and detailed conversation)')], max_length=200, null=True),
        ),
    ]
