# Generated by Django 3.1.7 on 2021-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0029_auto_20210710_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='support',
        ),
        migrations.AddField(
            model_name='session',
            name='support',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
