# Generated by Django 3.1.7 on 2021-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0031_session_urgent_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
