# Generated by Django 3.1.7 on 2021-09-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofiles', '0032_question_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='geographical',
            field=models.CharField(choices=[('East Palo Alto/Mountain View', 'East Palo Alto/Mountain View'), ('Menlo Park/Redwood City', 'Menlo Park/Redwood City'), ('San Mateo', 'San Mateo'), ('No preference', 'No preference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='geographical',
            field=models.CharField(choices=[('East Palo Alto/Mountain View', 'East Palo Alto/Mountain View'), ('Menlo Park/Redwood City', 'Menlo Park/Redwood City'), ('San Mateo', 'San Mateo'), ('No preference', 'No preference')], max_length=200),
        ),
    ]
