# Generated by Django 3.1.7 on 2021-04-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(max_length=1000)),
                ('challenge', models.TextField(max_length=1000)),
                ('notes', models.TextField(max_length=1000)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.connection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
