# Generated by Django 3.1.7 on 2021-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210418_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='subject',
        ),
        migrations.AddField(
            model_name='session',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='sessionsubjects', to='profiles.Subject'),
        ),
    ]
