# Generated by Django 3.1.7 on 2021-04-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_testprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('connected', 'connected'), ('disconnected', 'disconnected')], max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teststudent', to='profiles.testprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testtutor', to='profiles.testprofile')),
            ],
        ),
    ]
