# Generated by Django 3.1.7 on 2021-04-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
