# Generated by Django 3.1.7 on 2021-04-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='testprofile',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='TestConnection',
        ),
        migrations.DeleteModel(
            name='TestProfile',
        ),
    ]
