# Generated by Django 3.1.7 on 2021-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210421_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created',
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
