# Generated by Django 3.1.7 on 2021-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210421_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='challenge',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='notes',
            new_name='question',
        ),
        migrations.AddField(
            model_name='session',
            name='meet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
