# Generated by Django 3.1.7 on 2021-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20210423_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='othersupport',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
