# Generated by Django 3.1.7 on 2021-04-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_session_othersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='submit_status',
            field=models.BooleanField(default=False),
        ),
    ]
