# Generated by Django 3.1.7 on 2021-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_session_submit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
