# Generated by Django 3.1.7 on 2021-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20210423_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='change',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='cont',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='othersupport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
