# Generated by Django 3.1.7 on 2021-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20210505_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='feedback',
        ),
        migrations.AddField(
            model_name='session',
            name='feedback',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', to='profiles.Feedback'),
        ),
    ]
