# Generated by Django 3.1.7 on 2021-05-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20210505_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='cont',
            new_name='disconnect',
        ),
    ]
