# Generated by Django 3.1.7 on 2021-05-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20210505_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='eleborate',
            new_name='elaborate',
        ),
    ]
