# Generated by Django 3.1.7 on 2021-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20210505_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
