# Generated by Django 3.1.7 on 2021-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_session_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_advisor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
