# Generated by Django 3.1.7 on 2021-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20210508_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200, null=True),
        ),
    ]
