# Generated by Django 3.1.7 on 2021-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20210508_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reason_disconnect',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
