# Generated by Django 3.1.7 on 2021-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_session_reason_disconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_advisor_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
