# Generated by Django 3.1.7 on 2021-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_connection_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eighteen_older',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='not_grade_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
