# Generated by Django 3.1.7 on 2021-06-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
