# Generated by Django 3.1.7 on 2021-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_remove_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='profiles.Language'),
        ),
    ]
