# Generated by Django 3.1.7 on 2021-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_profile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent2_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent2_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent2_last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent2_phone',
        ),
    ]
