# Generated by Django 3.1.7 on 2021-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_auto_20210603_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_languages',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='profiles.Parentlanguage'),
        ),
    ]
