# Generated by Django 3.1.7 on 2021-06-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_profile_parent_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='elaborate',
        ),
        migrations.RemoveField(
            model_name='session',
            name='feedback',
        ),
    ]
