# Generated by Django 3.1.7 on 2021-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_auto_20210605_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
