# Generated by Django 3.1.7 on 2021-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_subjectcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcalculation',
            name='created',
        ),
        migrations.AddField(
            model_name='subjectcalculation',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
