# Generated by Django 3.1.7 on 2021-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20210606_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcalculation',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
