# Generated by Django 3.1.7 on 2021-06-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20210607_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjectcalculation',
        ),
    ]
