# Generated by Django 3.1.7 on 2021-06-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_delete_subjectcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectcalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
