# Generated by Django 3.1.7 on 2021-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_subjectcalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcalculation',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
