# Generated by Django 3.1.7 on 2021-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, choices=[('UNANSWERED', 'UNANSWERED'), ('ADDRESSED', 'ADDRESSED')], max_length=200, null=True),
        ),
    ]
