# Generated by Django 3.1.7 on 2021-06-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_auto_20210612_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Not in grade school', 'Not in grade school')], max_length=200, null=True),
        ),
    ]
