# Generated by Django 3.1.7 on 2021-06-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0066_auto_20210615_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='not_grade_school',
        ),
    ]
