# Generated by Django 3.1.7 on 2021-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_remove_profile_not_grade_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eighteen_older',
        ),
    ]
