# Generated by Django 3.1.7 on 2021-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0069_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_grade',
            field=models.CharField(blank=True, choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Not in grade school', 'Not in grade school')], max_length=200, null=True),
        ),
    ]
