# Generated by Django 3.1.7 on 2021-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0070_profile_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_grade',
            field=models.CharField(blank=True, choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=200, null=True),
        ),
    ]
