# Generated by Django 3.1.7 on 2021-06-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0071_auto_20210616_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='change',
        ),
    ]
