# Generated by Django 3.1.7 on 2021-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0072_remove_session_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='help',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
