# Generated by Django 3.1.7 on 2021-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0073_session_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
