# Generated by Django 3.1.7 on 2021-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0075_profile_ethnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='urgent_check',
            field=models.BooleanField(default=False),
        ),
    ]
