# Generated by Django 3.1.7 on 2021-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0076_session_urgent_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_languages',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200, null=True),
        ),
    ]
