# Generated by Django 3.1.7 on 2021-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0077_auto_20210714_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
