# Generated by Django 3.1.7 on 2021-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0078_auto_20210720_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
