# Generated by Django 3.1.7 on 2021-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0079_question_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='interest', to='profiles.Interest'),
        ),
    ]
