# Generated by Django 3.1.7 on 2021-09-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0081_auto_20210831_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
