# Generated by Django 3.1.7 on 2021-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0082_profile_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=200, null=True),
        ),
    ]
