# Generated by Django 3.1.7 on 2022-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0083_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connect_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Graduate', 'Graduate'), ('Professional', 'Professional')], max_length=200, null=True),
        ),
    ]
