# Generated by Django 3.1.7 on 2021-09-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_grade',
            field=models.CharField(blank=True, choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=200, null=True),
        ),
    ]
