# Generated by Django 3.1.7 on 2021-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleschool', '0002_auto_20210831_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_grade',
            field=models.CharField(blank=True, choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=200, null=True),
        ),
    ]
