# Generated by Django 3.1.7 on 2021-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleschool', '0003_auto_20210917_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=200, null=True),
        ),
    ]
