# Generated by Django 3.1.7 on 2021-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('grade', models.CharField(choices=[('5', '5'), ('8', '8')], max_length=200)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('parent_first_name', models.CharField(blank=True, max_length=200)),
                ('parent_last_name', models.CharField(blank=True, max_length=200)),
                ('parent_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=200)),
                ('parent_email', models.EmailField(blank=True, max_length=200)),
                ('activity', models.TextField(blank=True, max_length=1000, null=True)),
                ('reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('prompt', models.TextField(blank=True, max_length=1000, null=True)),
                ('hobby', models.TextField(blank=True, max_length=1000, null=True)),
                ('parent_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('interview_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('prefer_grade', models.CharField(choices=[('5', '5'), ('8', '8')], max_length=200)),
                ('prefer_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('prefer_location', models.CharField(blank=True, max_length=200)),
                ('mentor_last_year', models.BooleanField(default=False)),
                ('language', models.TextField(blank=True, max_length=1000, null=True)),
                ('experience', models.TextField(blank=True, max_length=1000, null=True)),
                ('familiar', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
