# Generated by Django 3.1.7 on 2021-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0002_mentor_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='cprofiles.Csprofile'),
        ),
    ]
