# Generated by Django 3.1.7 on 2021-04-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0005_connection_session_support_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
