# Generated by Django 3.1.7 on 2021-04-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0006_auto_20210430_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cprofiles.session')),
            ],
        ),
    ]
