# Generated by Django 3.1.7 on 2021-05-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0009_connection_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
