# Generated by Django 3.1.7 on 2021-05-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0013_auto_20210501_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
