# Generated by Django 3.1.7 on 2021-05-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0015_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tast10date',
            new_name='task10date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast1date',
            new_name='task1date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast2date',
            new_name='task2date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast3date',
            new_name='task3date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast4date',
            new_name='task4date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast5date',
            new_name='task5date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast6date',
            new_name='task6date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast7date',
            new_name='task7date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast8date',
            new_name='task8date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tast9date',
            new_name='task9date',
        ),
    ]
