# Generated by Django 3.1.7 on 2021-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0017_auto_20210501_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='progress',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
