# Generated by Django 3.1.7 on 2021-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0018_auto_20210501_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.CharField(blank=True, max_length=200, null=True)),
                ('task2', models.CharField(blank=True, max_length=200, null=True)),
                ('task3', models.CharField(blank=True, max_length=200, null=True)),
                ('task4', models.CharField(blank=True, max_length=200, null=True)),
                ('task5', models.CharField(blank=True, max_length=200, null=True)),
                ('task6', models.CharField(blank=True, max_length=200, null=True)),
                ('task7', models.CharField(blank=True, max_length=200, null=True)),
                ('task8', models.CharField(blank=True, max_length=200, null=True)),
                ('task9', models.CharField(blank=True, max_length=200, null=True)),
                ('task10', models.CharField(blank=True, max_length=200, null=True)),
                ('task1date', models.DateField(blank=True, max_length=200, null=True)),
                ('task2date', models.DateField(blank=True, max_length=200, null=True)),
                ('task3date', models.DateField(blank=True, max_length=200, null=True)),
                ('task4date', models.DateField(blank=True, max_length=200, null=True)),
                ('task5date', models.DateField(blank=True, max_length=200, null=True)),
                ('task6date', models.DateField(blank=True, max_length=200, null=True)),
                ('task7date', models.DateField(blank=True, max_length=200, null=True)),
                ('task8date', models.DateField(blank=True, max_length=200, null=True)),
                ('task9date', models.DateField(blank=True, max_length=200, null=True)),
                ('task10date', models.DateField(blank=True, max_length=200, null=True)),
                ('task1status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task2status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task3status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task4status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task5status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task6status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task7status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task8status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task9status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task10status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('progress', models.CharField(choices=[('on track', 'on track'), ('off track', 'off track')], max_length=200)),
                ('connection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cprofiles.connection')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cprofiles.student')),
            ],
        ),
    ]
