# Generated by Django 3.1.7 on 2021-05-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0021_delete_tasktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasksubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('duedate', models.DateField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
