# Generated by Django 3.1.7 on 2021-05-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0022_tasksubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField(blank=True, max_length=200, null=True)),
                ('progress', models.CharField(blank=True, choices=[('on track', 'on track'), ('off track', 'off track')], max_length=200, null=True)),
                ('connection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cprofiles.tasksubject')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cprofiles.student')),
            ],
        ),
    ]
