# Generated by Django 3.1.7 on 2021-05-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0023_tasktest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTest',
        ),
    ]
