# Generated by Django 3.1.7 on 2021-05-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0025_tasktest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktest',
            name='duedate',
        ),
    ]
