# Generated by Django 3.1.7 on 2021-05-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0028_auto_20210502_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
