# Generated by Django 3.1.7 on 2021-05-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0029_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTest',
            new_name='Task',
        ),
    ]
