# Generated by Django 3.1.7 on 2021-05-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0033_session_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copytask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task2status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task3status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task4status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task5status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task6status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task7status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task8status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task9status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('task10status', models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], max_length=200, null=True)),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cprofiles.session')),
                ('tasksubject', models.ManyToManyField(blank=True, to='cprofiles.Tasksubject')),
            ],
        ),
    ]
