# Generated by Django 3.1.7 on 2021-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0036_auto_20210508_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_advisor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_advisor_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
