# Generated by Django 3.1.7 on 2021-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0037_auto_20210522_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
