# Generated by Django 3.1.7 on 2021-06-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0041_auto_20210522_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
