# Generated by Django 3.1.7 on 2021-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0042_auto_20210602_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
