# Generated by Django 3.1.7 on 2021-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0043_session_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task8status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
    ]
