# Generated by Django 3.1.7 on 2021-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0044_auto_20210616_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task10status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task1status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task2status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task3status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task4status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task5status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task6status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task7status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task9status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=200, null=True),
        ),
    ]
