# Generated by Django 3.1.7 on 2021-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0045_auto_20210616_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interview_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=200, null=True),
        ),
    ]
