# Generated by Django 3.1.7 on 2021-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0046_auto_20210617_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('No preference', 'No preference')], max_length=200, null=True),
        ),
    ]
