# Generated by Django 3.1.7 on 2021-06-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0050_remove_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_language',
        ),
    ]
