# Generated by Django 3.1.7 on 2021-06-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0051_remove_student_parent_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ind_scl',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
