# Generated by Django 3.1.7 on 2021-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0052_auto_20210617_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentor',
            name='question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='share',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
