# Generated by Django 3.1.7 on 2021-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0053_auto_20210617_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.CharField(blank=True, choices=[('5', '5'), ('8', '8'), ('no preference', 'no preference')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_last_year',
            field=models.CharField(blank=True, choices=[('5', '5'), ('8', '8'), ('no preference', 'no preference')], max_length=200, null=True),
        ),
    ]
