# Generated by Django 3.1.7 on 2021-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0054_auto_20210617_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='prefer_location',
        ),
        migrations.AddField(
            model_name='mentor',
            name='prefer_location',
            field=models.ManyToManyField(blank=True, related_name='social_strength', to='cprofiles.Preferlocation'),
        ),
    ]
