# Generated by Django 3.1.7 on 2021-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0057_remove_session_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='elaborate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='productivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
