# Generated by Django 3.1.7 on 2021-06-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0058_auto_20210617_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('action', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('UNANSWERED', 'UNANSWERED'), ('ADDRESSED', 'ADDRESSED')], max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_question', to='cprofiles.mentor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_question', to='cprofiles.student')),
            ],
        ),
    ]
