# Generated by Django 3.1.7 on 2021-06-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0061_parentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='hobby',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
