# Generated by Django 3.1.7 on 2021-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0064_parentsession_urgent_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='urgent_check',
            field=models.BooleanField(default=False),
        ),
    ]
