# Generated by Django 3.1.7 on 2021-08-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0068_connection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prompt',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
