# Generated by Django 3.1.7 on 2021-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0069_student_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prompt',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='student',
            name='answer2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='question1',
            field=models.CharField(blank=True, choices=[('What was the first job you wanted as a kid?', 'What was the first job you wanted as a kid?'), ('If you were one of the seven dwarves in Snow White, which one would you be?', 'If you were one of the seven dwarves in Snow White, which one would you be?'), ('What is your guilty pleasure?', 'What is your guilty pleasure?'), ('What song do you sing in the shower?', 'What song do you sing in the shower?'), ('What is your biggest (non-serious) fear?', 'What is your biggest (non-serious) fear?'), ('What is your favorite binge-watching TV series?', 'What is your favorite binge-watching TV series?'), ('What would your last meal on Earth be?', 'What would your last meal on Earth be?'), ('Who is your favorite person in history?', 'Who is your favorite person in history?'), ('A trip you most want to take but haven’t yet?', 'A trip you most want to take but haven’t yet?')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='question2',
            field=models.CharField(blank=True, choices=[('What was the first job you wanted as a kid?', 'What was the first job you wanted as a kid?'), ('If you were one of the seven dwarves in Snow White, which one would you be?', 'If you were one of the seven dwarves in Snow White, which one would you be?'), ('What is your guilty pleasure?', 'What is your guilty pleasure?'), ('What song do you sing in the shower?', 'What song do you sing in the shower?'), ('What is your biggest (non-serious) fear?', 'What is your biggest (non-serious) fear?'), ('What is your favorite binge-watching TV series?', 'What is your favorite binge-watching TV series?'), ('What would your last meal on Earth be?', 'What would your last meal on Earth be?'), ('Who is your favorite person in history?', 'Who is your favorite person in history?'), ('A trip you most want to take but haven’t yet?', 'A trip you most want to take but haven’t yet?')], max_length=200, null=True),
        ),
    ]
