# Generated by Django 3.1.7 on 2021-09-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofiles', '0070_auto_20210806_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='prefer_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('No preference', 'No preference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('No preference', 'No preference')], max_length=200),
        ),
    ]
